print("Loaded constants.py")
# Display
SCREEN_WIDTH = 1280
print(f"Screen Width = {SCREEN_WIDTH}")
SCREEN_HEIGHT = 720
print(f"Screen Height = {SCREEN_HEIGHT}")

# Astroids
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

# Player
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3

# Shots
SHOT_RADIUS = 5